const APP_ID = "33zqFdSUnH9jY0bjdm8Vn";
const REDIRECT_URI = "https://bryceetrades.vercel.app/";
const CURRENCY = "USD";

let ws = null;
let token = localStorage.getItem('deriv_token');
let lastBalance = 0;
let balanceInterval = null;

function connectWS() {
  ws = new WebSocket(`wss://ws.derivws.com/websockets/v3?app_id=${APP_ID}`);
    
      ws.onopen = () => {
          if (token) {
                ws.send(JSON.stringify({ authorize: token }));
                    } else {
                          document.getElementById('loginBtn') && (document.getElementById('loginBtn').style.display = 'block');
                              }
                                };
                                  
                                    ws.onmessage = (msg) => {
                                        const data = JSON.parse(msg.data);
                                            if (data.error) { console.error(data.error.message); showStatus(data.error.message, 'red'); return; }
                                                
                                                    if (data.msg_type === 'authorize') {
                                                          // 1. Live balance stream
                                                                ws.send(JSON.stringify({ balance: 1, subscribe: 1 })); 
                                                                      // 2. Live trades
                                                                            ws.send(JSON.stringify({ portfolio: 1, subscribe: 1 }));
                                                                                  ws.send(JSON.stringify({ transaction: 1, subscribe: 1 }));
                                                                                        // 3. Live ticks
                                                                                              ws.send(JSON.stringify({ ticks: 'R_100', subscribe: 1 }));
                                                                                                    document.getElementById('loginBtn') && (document.getElementById('loginBtn').style.display = 'none');
                                                                                                          document.getElementById('logoutBtn') && (document.getElementById('logoutBtn').style.display = 'inline-block');
                                                                                                                document.getElementById('tradeBtn') && (document.getElementById('tradeBtn').style.display = 'block');
                                                                                                                    }
                                                                                                                        
                                                                                                                            if (data.msg_type === 'balance') {
                                                                                                                                  updateBalance(data.balance); // <-- Deriv nests it as data.balance
                                                                                                                                      }
                                                                                                                                          
                                                                                                                                              if (data.msg_type === 'tick') {
                                                                                                                                                    window.onTick && window.onTick(data.tick);
                                                                                                                                                        }
                                                                                                                                                            
                                                                                                                                                                if (data.msg_type === 'proposal') {
                                                                                                                                                                      window.onProposal && window.onProposal(data.proposal);
                                                                                                                                                                          }
                                                                                                                                                                              
                                                                                                                                                                                  if (data.msg_type === 'buy') {
                                                                                                                                                                                        showStatus('✓ Trade placed! ID: ' + data.buy.contract_id, '#4cd964');
                                                                                                                                                                                              startBalancePoll(); // Start polling when trade is active
                                                                                                                                                                                                    loadPortfolio();
                                                                                                                                                                                                        }
                                                                                                                                                                                                            
                                                                                                                                                                                                                if (data.msg_type === 'portfolio') {
                                                                                                                                                                                                                      renderPortfolio(data.portfolio.contracts || []);
                                                                                                                                                                                                                            if((data.portfolio.contracts || []).length === 0) stopBalancePoll(); // Stop polling when no trades
                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                        if (data.msg_type === 'transaction') {
                                                                                                                                                                                                                                              if (data.transaction.action === 'sell') {
                                                                                                                                                                                                                                                      loadPortfolio(); // Trade closed, refresh
                                                                                                                                                                                                                                                              ws.send(JSON.stringify({ balance: 1 })); // Force 1x balance fetch on close
                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                              ws.onclose = () => {
                                                                                                                                                                                                                                                                                  showStatus('Reconnecting...', '#ff9f0a');
                                                                                                                                                                                                                                                                                      stopBalancePoll();
                                                                                                                                                                                                                                                                                          setTimeout(connectWS, 2000);
                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                            connectWS();

                                                                                                                                                                                                                                                                                            function startBalancePoll() {
                                                                                                                                                                                                                                                                                              if (balanceInterval) return;
                                                                                                                                                                                                                                                                                                balanceInterval = setInterval(() => {
                                                                                                                                                                                                                                                                                                    if (ws.readyState === 1) ws.send(JSON.stringify({ balance: 1 })); // Force fetch every 3s
                                                                                                                                                                                                                                                                                                      }, 3000);
                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                      function stopBalancePoll() {
                                                                                                                                                                                                                                                                                                        clearInterval(balanceInterval);
                                                                                                                                                                                                                                                                                                          balanceInterval = null;
                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                          function updateBalance(newBal) {
                                                                                                                                                                                                                                                                                                            const el = document.getElementById('balance');
                                                                                                                                                                                                                                                                                                              if (!el) return;
                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                  newBal = parseFloat(newBal);
                                                                                                                                                                                                                                                                                                                    if (lastBalance !== 0 && newBal !== lastBalance) {
                                                                                                                                                                                                                                                                                                                        el.style.color = newBal > lastBalance ? '#4cd964' : '#ff3b30';
                                                                                                                                                                                                                                                                                                                            setTimeout(() => el.style.color = '#0057ff', 800);
                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                lastBalance = newBal;
                                                                                                                                                                                                                                                                                                                                  el.innerText = newBal.toFixed(2) + ' USD';
                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                  function loadPortfolio() {
                                                                                                                                                                                                                                                                                                                                    if (ws.readyState === 1) ws.send(JSON.stringify({ portfolio: 1 }));
                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                    function showStatus(msg, color='#888') {
                                                                                                                                                                                                                                                                                                                                      const el = document.getElementById('status');
                                                                                                                                                                                                                                                                                                                                        if (el) {
                                                                                                                                                                                                                                                                                                                                            el.innerText = msg;
                                                                                                                                                                                                                                                                                                                                                el.style.color = color;
                                                                                                                                                                                                                                                                                                                                                    if (color !== 'red') setTimeout(() => el.innerText = '', 3000);
                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                      function login() {
                                                                                                                                                                                                                                                                                                                                                        const appUrl = `https://oauth.deriv.com/oauth2/authorize?app_id=${APP_ID}&redirect_uri=${REDIRECT_URI}`;
                                                                                                                                                                                                                                                                                                                                                          window.location.href = appUrl;
                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                          function getTokenFromURL() {
                                                                                                                                                                                                                                                                                                                                                            const hash = window.location.hash;
                                                                                                                                                                                                                                                                                                                                                              if (hash.includes('token1=')) {
                                                                                                                                                                                                                                                                                                                                                                  const t = hash.split('token1=')[1].split('&')[0];
                                                                                                                                                                                                                                                                                                                                                                      localStorage.setItem('deriv_token', t);
                                                                                                                                                                                                                                                                                                                                                                          window.location.hash = '';
                                                                                                                                                                                                                                                                                                                                                                              location.reload();
                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                getTokenFromURL();

                                                                                                                                                                                                                                                                                                                                                                                function logout() {
                                                                                                                                                                                                                                                                                                                                                                                  localStorage.removeItem('deriv_token');
                                                                                                                                                                                                                                                                                                                                                                                    location.href = 'index.html';
                                                                                                                                                                                                                                                                                                                                                                                    }
